Repository todolist-team2/todo-max, pull requests merged in 2023-07, with the labels that each got.

#3 [BE] 카드 등록
  backend/src/main/java/kr/codesquad/todo/controller/CardController.java
  backend/src/main/java/kr/codesquad/todo/domain/Card.java
  backend/src/main/java/kr/codesquad/todo/dto/request/CardCreationRequest.java
  backend/src/main/java/kr/codesquad/todo/exeption/BusinessException.java
  backend/src/main/java/kr/codesquad/todo/exeption/ErrorCode.java
  backend/src/main/java/kr/codesquad/todo/exeption/ErrorResponse.java
  backend/src/main/java/kr/codesquad/todo/exeption/GlobalExceptionHandler.java
  backend/src/main/java/kr/codesquad/todo/repository/CardRepository.java
  backend/src/main/java/kr/codesquad/todo/repository/CategoryRepository.java
  backend/src/main/java/kr/codesquad/todo/service/CardService.java
  backend/src/test/java/kr/codesquad/todo/controller/CardControllerTest.java
  backend/src/test/java/kr/codesquad/todo/fixture/FixtureFactory.java
  backend/src/test/java/kr/codesquad/todo/service/CardServiceTest.java
Labels: ✨feat

#13 [BE] 카드 목록 조회
  backend/src/main/java/kr/codesquad/todo/controller/CardController.java
  backend/src/main/java/kr/codesquad/todo/dto/response/CardData.java
  backend/src/main/java/kr/codesquad/todo/dto/response/CardsResponse.java
  backend/src/main/java/kr/codesquad/todo/dto/response/CategoryResponse.java
  backend/src/main/java/kr/codesquad/todo/repository/CardRepository.java
  backend/src/main/java/kr/codesquad/todo/service/CardService.java
  backend/src/test/java/kr/codesquad/todo/acceptance/TodoTest.java
Labels: ✨feat, 💻BE

#12 [BE] 카드 수정 기능 구현
  backend/build.gradle
  backend/src/main/java/kr/codesquad/todo/controller/CardController.java
  backend/src/main/java/kr/codesquad/todo/repository/CardRepository.java
  backend/src/main/java/kr/codesquad/todo/service/CardService.java
  backend/src/test/java/kr/codesquad/todo/acceptance/TodoTest.java
Labels: ✨feat, 💻BE

#14 [BE] 카드 이동
  backend/src/main/java/kr/codesquad/todo/controller/CardController.java
  backend/src/main/java/kr/codesquad/todo/dto/request/CardMoveRequest.java
  backend/src/main/java/kr/codesquad/todo/repository/CardRepository.java
  backend/src/main/java/kr/codesquad/todo/service/CardService.java
  backend/src/test/java/kr/codesquad/todo/acceptance/DatabaseAccessor.java
  backend/src/test/java/kr/codesquad/todo/acceptance/DatabaseInitializer.java
  backend/src/test/java/kr/codesquad/todo/acceptance/TodoTest.java
  backend/src/test/java/kr/codesquad/todo/controller/CardControllerTest.java
  backend/src/test/java/kr/codesquad/todo/fixture/FixtureFactory.java
  backend/src/test/java/kr/codesquad/todo/service/CardServiceTest.java
Labels: ✨feat, 💻BE

#17 [BE] 활동 기록 관련 기능
  backend/src/main/java/kr/codesquad/todo/controller/ActionController.java
  backend/src/main/java/kr/codesquad/todo/domain/Action.java
  backend/src/main/java/kr/codesquad/todo/dto/response/ActionResponse.java
  backend/src/main/java/kr/codesquad/todo/dto/response/Slice.java
  backend/src/main/java/kr/codesquad/todo/repository/ActionRepository.java
  backend/src/main/java/kr/codesquad/todo/service/ActionService.java
Labels: ✨feat, 💻BE

#26 [BE] 테이블 스키마 변경
  backend/src/main/resources/schema.sql
  backend/src/test/resources/schema.sql
Labels: 💻BE, 🔧fix

#30 [BE] 활동기록 등록
  backend/src/main/java/kr/codesquad/todo/controller/CardController.java
  backend/src/main/java/kr/codesquad/todo/domain/ActionType.java
  backend/src/main/java/kr/codesquad/todo/dto/ActionData.java
  backend/src/main/java/kr/codesquad/todo/dto/response/ActionResponse.java
  backend/src/main/java/kr/codesquad/todo/repository/ActionRepository.java
  backend/src/main/java/kr/codesquad/todo/repository/CardRepository.java
  backend/src/main/java/kr/codesquad/todo/repository/CategoryRepository.java
  backend/src/main/java/kr/codesquad/todo/service/ActionService.java
  backend/src/main/java/kr/codesquad/todo/service/CardService.java
  backend/src/test/java/kr/codesquad/todo/fixture/FixtureFactory.java
  backend/src/test/java/kr/codesquad/todo/integration/CardTest.java
  backend/src/test/java/kr/codesquad/todo/service/CardServiceTest.java
  backend/src/test/java/kr/codesquad/todo/service/CategoryServiceTest.java
Labels: ✨feat, 💻BE

#31 [FE] 공통 컴포넌트 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/close-danger.svg
  frontend/public/close.svg
  frontend/public/edit.svg
  frontend/public/log.svg
  frontend/public/plus.svg
  frontend/src/App.tsx
  frontend/src/components/Board.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/HistoryBtn.tsx
  frontend/src/components/Logo.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/aside/Aside.tsx
  frontend/src/components/aside/actionHistory/UserActionLog.tsx
  frontend/src/components/aside/actionHistory/UserActionLogList.tsx
  frontend/src/components/common/Alert.tsx
  frontend/src/components/common/Badge.tsx
  frontend/src/components/common/Buttons.tsx
  frontend/src/components/common/Fab.tsx
  frontend/src/components/common/Icon.tsx
  frontend/src/components/landmark/Header.tsx
  frontend/src/components/landmark/Main.tsx
  frontend/src/components/landmark/landmark.tsx
  frontend/src/components/main/Main.tsx
  frontend/src/components/main/board/Board.tsx
  frontend/src/components/main/board/column/Column.tsx
  frontend/src/components/main/board/column/ColumnControl.tsx
  frontend/src/components/main/board/column/ColumnTitle.tsx
  frontend/src/components/main/board/column/card/Card.tsx
  frontend/src/hooks/useAlert.ts
  frontend/src/main.tsx
  frontend/src/styles/CommonStyle.tsx
  frontend/src/styles/Container.tsx
  frontend/src/styles/Dim.tsx
  frontend/src/theme.ts
  frontend/src/types/TAlertState.ts
  frontend/src/types/TCard.ts
  frontend/src/types/TColumn.ts
  frontend/src/types/TTheme.ts
  package-lock.json
Labels: ✨feat, ⚙️refactor, 🪄chore, 💻FE

#35 [FE] 카드 수정 기능
  frontend/src/components/common/Buttons.tsx
  frontend/src/components/main/board/Board.tsx
  frontend/src/components/main/board/column/Column.tsx
  frontend/src/components/main/board/column/card/Card.tsx
  frontend/src/components/main/board/column/card/CardForm.tsx
  frontend/src/mocks/handlers.ts
Labels: ✨feat, 💻FE

#38 [BE] 활동 기록 관련 리팩토링
  backend/build.gradle
  backend/src/main/java/kr/codesquad/todo/controller/ActionController.java
  backend/src/main/java/kr/codesquad/todo/controller/CardController.java
  backend/src/main/java/kr/codesquad/todo/domain/Action.java
  backend/src/main/java/kr/codesquad/todo/domain/Category.java
  backend/src/main/java/kr/codesquad/todo/dto/response/ActionData.java
  backend/src/main/java/kr/codesquad/todo/dto/response/ActionResponse.java
  backend/src/main/java/kr/codesquad/todo/dto/response/Slice.java
  backend/src/main/java/kr/codesquad/todo/repository/ActionRepository.java
  backend/src/main/java/kr/codesquad/todo/repository/CardRepository.java
  backend/src/main/java/kr/codesquad/todo/service/ActionService.java
  backend/src/main/java/kr/codesquad/todo/service/CardService.java
  backend/src/main/resources/application-h2.yml
  backend/src/test/java/kr/codesquad/todo/acceptance/TodoTest.java
  backend/src/test/java/kr/codesquad/todo/controller/CardControllerTest.java
  backend/src/test/java/kr/codesquad/todo/service/CardServiceTest.java
Labels: ⚙️refactor, 💻BE

#45 [BE] CORS
  backend/src/main/java/kr/codesquad/todo/config/WebConfig.java
Labels: ✨feat, 💻BE

#43 [FE] ActionHistory 컴포넌트 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/aside/ActionHistoryItem.tsx
  frontend/src/components/aside/ActionHistoryList.tsx
  frontend/src/components/aside/Aside.tsx
  frontend/src/hooks/useSetStateStore.ts
  frontend/src/main.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/theme.ts
  frontend/src/utils/deleteActions.ts
  frontend/src/utils/updateActions.ts
Labels: ✨feat, 💻FE

#46 [FE] 카드 이동 기능 구현
  frontend/src/components/main/board/Board.tsx
  frontend/src/components/main/board/column/Column.tsx
  frontend/src/components/main/board/column/card/Card.tsx
  frontend/src/components/main/board/column/card/CardShadow.tsx
  frontend/src/mocks/handlers.ts
Labels: ✨feat, 💻FE

#48 [FE] 서버와 연동 테스트 및 버그 수정
  frontend/package.json
  frontend/src/components/main/Main.tsx
  frontend/src/components/main/board/Board.tsx
  frontend/src/components/main/board/column/Column.tsx
  frontend/src/components/main/board/column/card/Card.tsx
  frontend/src/contexts/DragContext.tsx
  frontend/src/main.tsx
  frontend/src/utils/fetch.ts
Labels: ✨feat, 💻FE
